name: 08-basics-variables

run-name: ${{ github.actor }} explaining variables - Try Number ${{ github.run_number }}

env:
  MY_NAME: "khaled Abd albasit"
on:
  workflow_dispatch:

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: echo $MY_NAME
