name: 08-basics-variables

run-name: ${{ github.actor }} explaining variables - Try Number ${{ github.run_number }}

on:
  workflow_dispatch:

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: echo "Hello world"
